server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**, /api/auth/**
        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/api/task/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka