server:
  port: 8082

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket: tasks
  secure: false

spring:
  application:
    name: task-service


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true



  datasource:
    url: jdbc:postgresql://localhost:5432/exam_platform
    username: admin
    password: p@ssw0rd_f0r_db
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

app:
  security:
    jwt:
      enabled: true
      secret: SFJAKLJakxlfjkljSakjAKLDJASKLDsadkmasdklasdjSDJSKLJSDALJsxm,adnsml,
      expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG